# target: all - Default target. Currently just compiles the TypeScript files into JavaScript.
all: clean build-js



### Targets below here are generally just called from the targets above.

# target: build-js - Compiles the TypeScript files into JavaScript
build-js:
	tsc --sourcemap --out gen/app.js ts/app.ts

# target: clean - Delete files generated by `make all`.
clean:
	rm -f gen/app.js
	rm -f gen/app.js.map



###

.PHONY: all build-js clean