# target: all - Default target. Currently just compiles the TypeScript files into JavaScript.
all: clean build-js

# target: check - Run unit tests
check:
	./node_modules/karma/bin/karma start karma.conf.js

# target: install-npm-deps - Install npm dependencies to node_modules
install-npm-deps:
	sudo npm install # Not sure why sudo is needed, but it is on my computer


### Targets below here are generally just called from the targets above.

# target: build-js - Compiles the TypeScript files into JavaScript
build-js:
	tsc --noImplicitAny --target ES5 --sourcemap --out gen/app.js ts/app.ts

# target: clean - Delete files generated by `make all`.
clean:
	rm -f gen/app.js
	rm -f gen/app.js.map



###

.PHONY: all build-js clean